### PR TITLE
Minor fixes in documentation

### PR DESCRIPTION
**Pull request by sanket-buyhatke**

### CODE REVIEW

**Comment by shibbyy** [comment]
@sanket-buyhatke new coins are added here, did you test them?

**Comment by sanket-buyhatke** [comment]
yes @karmendra checked them, Substratum and Loopring dont seem to work yet.

**Comment by karmendra** [comment]
I have no clue about this repository and I promise I have checked nothing. I think you wanted to mention some other karmendra.

**Comment by sanket-buyhatke** [comment]
yes, i meant karmendra (intern)

**Pull request merged**
